version: '3.3'

services:

  appJEE:
    image: appjee
    build: .
    restart: always
    ports:
      - 8585:8080

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

volumes:
  db: